# spring params
spring:
  application:
    name: dispatcher
#  activemq:
#    in-memory: false
#    broker-url: tcp://localhost:61616?jms.redeliveryPolicy.redeliveryDelay=5000&jms.redeliveryPolicy.maximumRedeliveries=-1
#    user: karaf
#    password: karaf
  cloud:
    zookeeper:
      connect-string: ${zooHost}:2181
#      dependencies:
#          agent:
#              path: /agent
#              loadBalancerType: ROUND_ROBIN
#              contentTypeTemplate: application/json
#              version: v1
#              required: false
  data:
      mongodb:
        host: ${mongoHost}


# embedded server params
server:
  port: ${port}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

# logging params
logging:
  file: application.log
  level:
    org.apache.zookeeper.ClientCnxn: WARN

# auth params
auth:
  server:
    token_url: http://${authHost}:8088/oauth/token

#activemq
activemq:
  host: tcp://${amqHost}:61616
  user: karaf
  pass: karaf
  queue: events
  redeliveryDelay: 5000
  maxRedeliveries: -1

# activemq topic
##spring.jms.pub-sub-domain: true
spring.jms.listener.acknowledge-mode: CLIENT
